services:
  backend:
    build:
      context: ./backend-db
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - MONGO_ATLAS_URL=${MONGO_ATLAS_URL}
      - SOCKET_PORT=${SOCKET_PORT}
      - EXPRESS_PORT=${EXPRESS_PORT}
      - TOKEN_STRING=${TOKEN_STRING}
    ports:
      - ${EXPRESS_PORT}:${EXPRESS_PORT}
      - ${SOCKET_PORT}:${SOCKET_PORT}
    depends_on:
      - mongodb
    volumes:
      - ./backend-db:/app
      - /app/node_modules  
 
  
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MY_DB_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MY_DB_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: ${MONGO_URL}
  #     ME_CONFIG_BASICAUTH: false

  # mongodb:
  #   image: mongo:latest
  #   container_name: mongodb_container
  #   volumes:
  #     - ./data:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #     MONGO_INITDB_DATABASE: forrealdatingup

  #   ports:
  #     - "27018:27017"
   


